// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gen/helper"

	"gorm.io/plugin/dbresolver"

	"gorm.io/gen/tests/fixture/model"
)

func newUser(db *gorm.DB, opts ...gen.DOOption) user {
	_user := user{}

	_user.userDo.UseDB(db, opts...)
	_user.userDo.UseModel(&model.User{})

	tableName := _user.userDo.TableName()
	_user.ALL = field.NewAsterisk(tableName)
	_user.ID = field.NewUint(tableName, "id")
	_user.Name = field.NewString(tableName, "name")
	_user.Age = field.NewInt(tableName, "age")
	_user.Active = field.NewBool(tableName, "active")
	_user.Role = field.NewString(tableName, "role")
	_user.CompanyID = field.NewUint(tableName, "company_id")
	_user.Orders = userHasManyOrders{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Orders", "model.Order"),
		User: struct {
			field.RelationField
			Company struct {
				field.RelationField
				Users struct {
					field.RelationField
				}
			}
			Orders struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Orders.User", "model.User"),
			Company: struct {
				field.RelationField
				Users struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Orders.User.Company", "model.Company"),
				Users: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Orders.User.Company.Users", "model.User"),
				},
			},
			Orders: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Orders.User.Orders", "model.Order"),
			},
		},
	}

	_user.Company = userBelongsToCompany{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Company", "model.Company"),
		Users: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Company.Users", "model.User"),
		},
	}

	_user.fillFieldMap()

	return _user
}

type user struct {
	userDo userDo

	ALL       field.Asterisk
	ID        field.Uint
	Name      field.String
	Age       field.Int
	Active    field.Bool
	Role      field.String
	CompanyID field.Uint
	Orders    userHasManyOrders

	Company userBelongsToCompany

	fieldMap map[string]field.Expr
}

func (u user) Table(newTableName string) *user {
	u.userDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u user) As(alias string) *user {
	u.userDo.DO = *(u.userDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *user) updateTableName(table string) *user {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewUint(table, "id")
	u.Name = field.NewString(table, "name")
	u.Age = field.NewInt(table, "age")
	u.Active = field.NewBool(table, "active")
	u.Role = field.NewString(table, "role")
	u.CompanyID = field.NewUint(table, "company_id")

	u.fillFieldMap()

	return u
}

func (u *user) WithContext(ctx context.Context) IUserDo { return u.userDo.WithContext(ctx) }

func (u user) TableName() string { return u.userDo.TableName() }

func (u user) Alias() string { return u.userDo.Alias() }

func (u user) Columns(cols ...field.Expr) gen.Columns { return u.userDo.Columns(cols...) }

func (u *user) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *user) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 8)
	u.fieldMap["id"] = u.ID
	u.fieldMap["name"] = u.Name
	u.fieldMap["age"] = u.Age
	u.fieldMap["active"] = u.Active
	u.fieldMap["role"] = u.Role
	u.fieldMap["company_id"] = u.CompanyID

}

func (u user) clone(db *gorm.DB) user {
	u.userDo.ReplaceConnPool(db.Statement.ConnPool)
	u.Orders.db = db.Session(&gorm.Session{Initialized: true})
	u.Orders.db.Statement.ConnPool = db.Statement.ConnPool
	u.Company.db = db.Session(&gorm.Session{Initialized: true})
	u.Company.db.Statement.ConnPool = db.Statement.ConnPool
	return u
}

func (u user) replaceDB(db *gorm.DB) user {
	u.userDo.ReplaceDB(db)
	u.Orders.db = db.Session(&gorm.Session{})
	u.Company.db = db.Session(&gorm.Session{})
	return u
}

type userHasManyOrders struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
		Company struct {
			field.RelationField
			Users struct {
				field.RelationField
			}
		}
		Orders struct {
			field.RelationField
		}
	}
}

func (a userHasManyOrders) Where(conds ...field.Expr) *userHasManyOrders {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userHasManyOrders) WithContext(ctx context.Context) *userHasManyOrders {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userHasManyOrders) Session(session *gorm.Session) *userHasManyOrders {
	a.db = a.db.Session(session)
	return &a
}

func (a userHasManyOrders) Model(m *model.User) *userHasManyOrdersTx {
	return &userHasManyOrdersTx{a.db.Model(m).Association(a.Name())}
}

func (a userHasManyOrders) Unscoped() *userHasManyOrders {
	a.db = a.db.Unscoped()
	return &a
}

type userHasManyOrdersTx struct{ tx *gorm.Association }

func (a userHasManyOrdersTx) Find() (result []*model.Order, err error) {
	return result, a.tx.Find(&result)
}

func (a userHasManyOrdersTx) Append(values ...*model.Order) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userHasManyOrdersTx) Replace(values ...*model.Order) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userHasManyOrdersTx) Delete(values ...*model.Order) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userHasManyOrdersTx) Clear() error {
	return a.tx.Clear()
}

func (a userHasManyOrdersTx) Count() int64 {
	return a.tx.Count()
}

func (a userHasManyOrdersTx) Unscoped() *userHasManyOrdersTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userBelongsToCompany struct {
	db *gorm.DB

	field.RelationField

	Users struct {
		field.RelationField
	}
}

func (a userBelongsToCompany) Where(conds ...field.Expr) *userBelongsToCompany {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userBelongsToCompany) WithContext(ctx context.Context) *userBelongsToCompany {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userBelongsToCompany) Session(session *gorm.Session) *userBelongsToCompany {
	a.db = a.db.Session(session)
	return &a
}

func (a userBelongsToCompany) Model(m *model.User) *userBelongsToCompanyTx {
	return &userBelongsToCompanyTx{a.db.Model(m).Association(a.Name())}
}

func (a userBelongsToCompany) Unscoped() *userBelongsToCompany {
	a.db = a.db.Unscoped()
	return &a
}

type userBelongsToCompanyTx struct{ tx *gorm.Association }

func (a userBelongsToCompanyTx) Find() (result *model.Company, err error) {
	return result, a.tx.Find(&result)
}

func (a userBelongsToCompanyTx) Append(values ...*model.Company) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userBelongsToCompanyTx) Replace(values ...*model.Company) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userBelongsToCompanyTx) Delete(values ...*model.Company) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userBelongsToCompanyTx) Clear() error {
	return a.tx.Clear()
}

func (a userBelongsToCompanyTx) Count() int64 {
	return a.tx.Count()
}

func (a userBelongsToCompanyTx) Unscoped() *userBelongsToCompanyTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userDo struct{ gen.DO }

type IUserDo interface {
	gen.SubQuery
	Debug() IUserDo
	WithContext(ctx context.Context) IUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserDo
	WriteDB() IUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserDo
	Not(conds ...gen.Condition) IUserDo
	Or(conds ...gen.Condition) IUserDo
	Select(conds ...field.Expr) IUserDo
	Where(conds ...gen.Condition) IUserDo
	Order(conds ...field.Expr) IUserDo
	Distinct(cols ...field.Expr) IUserDo
	Omit(cols ...field.Expr) IUserDo
	Join(table schema.Tabler, on ...field.Expr) IUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserDo
	Group(cols ...field.Expr) IUserDo
	Having(conds ...gen.Condition) IUserDo
	Limit(limit int) IUserDo
	Offset(offset int) IUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserDo
	Unscoped() IUserDo
	Create(values ...*model.User) error
	CreateInBatches(values []*model.User, batchSize int) error
	Save(values ...*model.User) error
	First() (*model.User, error)
	Take() (*model.User, error)
	Last() (*model.User, error)
	Find() ([]*model.User, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.User, err error)
	FindInBatches(result *[]*model.User, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.User) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserDo
	Assign(attrs ...field.AssignExpr) IUserDo
	Joins(fields ...field.RelationField) IUserDo
	Preload(fields ...field.RelationField) IUserDo
	FirstOrInit() (*model.User, error)
	FirstOrCreate() (*model.User, error)
	FindByPage(offset int, limit int) (result []*model.User, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	FindByNameBranch(name string, active bool) (result []*model.User, err error)
	FindByNames(names []string) (result []*model.User, err error)
	FindByAttributes(attributes map[string]string) (result []*model.User, err error)
	UpdateOptional(id uint, name string, age int) (rowsAffected int64, err error)
	FindWithTrim(names []string) (result []*model.User, err error)
	InsertUser(name string, age int, active bool, role string, companyID uint) (rowsAffected int64, err error)
}

// FindByNameBranch chooses a name filter when supplied and an active filter otherwise.
//
// SELECT * FROM @@table
// {{where}}
// {{if name != ""}}
// name = @name
// {{else}}
// active = @active
// {{end}}
// {{end}}
func (u userDo) FindByNameBranch(name string, active bool) (result []*model.User, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM users ")
	var whereSQL0 strings.Builder
	if name != "" {
		params = append(params, name)
		whereSQL0.WriteString("name = ? ")
	} else {
		params = append(params, active)
		whereSQL0.WriteString("active = ? ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// FindByNames builds an OR list. An empty list intentionally has no WHERE clause.
//
// SELECT * FROM @@table
// {{where}}
// {{for _, name := range names}}
// OR name = @name
// {{end}}
// {{end}}
func (u userDo) FindByNames(names []string) (result []*model.User, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM users ")
	var whereSQL0 strings.Builder
	for _, name := range names {
		params = append(params, name)
		whereSQL0.WriteString("OR name = ? ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// FindByAttributes applies every supplied string attribute as an AND predicate.
//
// SELECT * FROM @@table
// {{where}}
// {{for column, value := range attributes}}
// AND @@column = @value
// {{end}}
// {{end}}
func (u userDo) FindByAttributes(attributes map[string]string) (result []*model.User, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM users ")
	var whereSQL0 strings.Builder
	for column, value := range attributes {
		params = append(params, value)
		whereSQL0.WriteString("AND " + u.Quote(column) + " = ? ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// UpdateOptional updates requested values and remains valid when both are omitted.
//
// UPDATE @@table
// {{set}}
// {{if name != ""}}
// name = @name,
// {{else}}
// name = name,
// {{end}}
// {{if age > 0}}
// age = @age,
// {{end}}
// {{end}}
// WHERE id = @id
func (u userDo) UpdateOptional(id uint, name string, age int) (rowsAffected int64, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("UPDATE users ")
	var setSQL0 strings.Builder
	if name != "" {
		params = append(params, name)
		setSQL0.WriteString("name = ?, ")
	} else {
		setSQL0.WriteString("name = name, ")
	}
	if age > 0 {
		params = append(params, age)
		setSQL0.WriteString("age = ?, ")
	}
	helper.JoinSetBuilder(&generateSQL, setSQL0)
	params = append(params, id)
	generateSQL.WriteString("WHERE id = ? ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	rowsAffected = executeSQL.RowsAffected
	err = executeSQL.Error

	return
}

// FindWithTrim trims the trailing OR and falls back to an always-false predicate.
//
// SELECT * FROM @@table WHERE
// {{trim}}
// {{for _, name := range names}}
// name = @name OR
// {{end}}
// id < 0
// {{end}}
func (u userDo) FindWithTrim(names []string) (result []*model.User, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM users WHERE ")
	var trimSQL0 strings.Builder
	for _, name := range names {
		params = append(params, name)
		trimSQL0.WriteString("name = ? OR ")
	}
	trimSQL0.WriteString("id < 0 ")
	helper.JoinTrimAllBuilder(&generateSQL, trimSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// InsertUser is intentionally dialect-neutral.
//
// INSERT INTO @@table (name, age, active, role, company_id)
// VALUES (@name, @age, @active, @role, @companyID)
func (u userDo) InsertUser(name string, age int, active bool, role string, companyID uint) (rowsAffected int64, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	params = append(params, age)
	params = append(params, active)
	params = append(params, role)
	params = append(params, companyID)
	generateSQL.WriteString("INSERT INTO users (name, age, active, role, company_id) VALUES (?, ?, ?, ?, ?) ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	rowsAffected = executeSQL.RowsAffected
	err = executeSQL.Error

	return
}

func (u userDo) Debug() IUserDo {
	return u.withDO(u.DO.Debug())
}

func (u userDo) WithContext(ctx context.Context) IUserDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userDo) ReadDB() IUserDo {
	return u.Clauses(dbresolver.Read)
}

func (u userDo) WriteDB() IUserDo {
	return u.Clauses(dbresolver.Write)
}

func (u userDo) Session(config *gorm.Session) IUserDo {
	return u.withDO(u.DO.Session(config))
}

func (u userDo) Clauses(conds ...clause.Expression) IUserDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userDo) Returning(value interface{}, columns ...string) IUserDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userDo) Not(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userDo) Or(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userDo) Select(conds ...field.Expr) IUserDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userDo) Where(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userDo) Order(conds ...field.Expr) IUserDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userDo) Distinct(cols ...field.Expr) IUserDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userDo) Omit(cols ...field.Expr) IUserDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userDo) Join(table schema.Tabler, on ...field.Expr) IUserDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userDo) Group(cols ...field.Expr) IUserDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userDo) Having(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userDo) Limit(limit int) IUserDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userDo) Offset(offset int) IUserDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userDo) Unscoped() IUserDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userDo) Create(values ...*model.User) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userDo) CreateInBatches(values []*model.User, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userDo) Save(values ...*model.User) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userDo) First() (*model.User, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.User), nil
	}
}

func (u userDo) Take() (*model.User, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.User), nil
	}
}

func (u userDo) Last() (*model.User, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.User), nil
	}
}

func (u userDo) Find() ([]*model.User, error) {
	result, err := u.DO.Find()
	return result.([]*model.User), err
}

func (u userDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.User, err error) {
	buf := make([]*model.User, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userDo) FindInBatches(result *[]*model.User, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userDo) Attrs(attrs ...field.AssignExpr) IUserDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userDo) Assign(attrs ...field.AssignExpr) IUserDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userDo) Joins(fields ...field.RelationField) IUserDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userDo) Preload(fields ...field.RelationField) IUserDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userDo) FirstOrInit() (*model.User, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.User), nil
	}
}

func (u userDo) FirstOrCreate() (*model.User, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.User), nil
	}
}

func (u userDo) FindByPage(offset int, limit int) (result []*model.User, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userDo) Delete(models ...*model.User) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userDo) withDO(do gen.Dao) *userDo {
	u.DO = *do.(*gen.DO)
	return u
}
