// Code generated by "stringer -type=BasicMethod -trimprefix method"; DO NOT EDIT.

package gen

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[methodDiy-0]
	_ = x[methodSelect-1]
	_ = x[methodWhere-2]
	_ = x[methodOrder-3]
	_ = x[methodDistinct-4]
	_ = x[methodOmit-5]
	_ = x[methodNot-6]
	_ = x[methodOr-7]
	_ = x[methodJoin-8]
	_ = x[methodGroup-9]
	_ = x[methodHaving-10]
	_ = x[methodLimit-11]
	_ = x[methodOffset-12]
	_ = x[methodScopes-13]
	_ = x[methodPreload-14]
	_ = x[methodAttrs-15]
	_ = x[methodAssign-16]
	_ = x[methodUnscoped-17]
	_ = x[methodCreate-18]
	_ = x[methodCreateInBatches-19]
	_ = x[methodSave-20]
	_ = x[methodFirst-21]
	_ = x[methodTake-22]
	_ = x[methodLast-23]
	_ = x[methodFind-24]
	_ = x[methodFindInBatches-25]
	_ = x[methodFirstOrInit-26]
	_ = x[methodFirstOrCreate-27]
	_ = x[methodUpdate-28]
	_ = x[methodUpdates-29]
	_ = x[methodUpdateColumn-30]
	_ = x[methodUpdateColumns-31]
	_ = x[methodDelete-32]
	_ = x[methodCount-33]
	_ = x[methodRow-34]
	_ = x[methodRows-35]
	_ = x[methodScan-36]
	_ = x[methodPluck-37]
	_ = x[methodScanRows-38]
	_ = x[methodTransaction-39]
	_ = x[methodBegin-40]
	_ = x[methodCommit-41]
	_ = x[methodRollback-42]
	_ = x[methodSavePoint-43]
	_ = x[methodRollbackTo-44]
}

const _BasicMethod_name = "DiySelectWhereOrderDistinctOmitNotOrJoinGroupHavingLimitOffsetScopesPreloadAttrsAssignUnscopedCreateCreateInBatchesSaveFirstTakeLastFindFindInBatchesFirstOrInitFirstOrCreateUpdateUpdatesUpdateColumnUpdateColumnsDeleteCountRowRowsScanPluckScanRowsTransactionBeginCommitRollbackSavePointRollbackTo"

var _BasicMethod_index = [...]uint16{0, 3, 9, 14, 19, 27, 31, 34, 36, 40, 45, 51, 56, 62, 68, 75, 80, 86, 94, 100, 115, 119, 124, 128, 132, 136, 149, 160, 173, 179, 186, 198, 211, 217, 222, 225, 229, 233, 238, 246, 257, 262, 268, 276, 285, 295}

func (i BasicMethod) String() string {
	if i >= BasicMethod(len(_BasicMethod_index)-1) {
		return "BasicMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BasicMethod_name[_BasicMethod_index[i]:_BasicMethod_index[i+1]]
}
