// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

/*
User table multiline /*comment* /
line1
line2
*/
type User struct {
	ID           int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"-"`
	CreatedAt    *time.Time `gorm:"column:created_at" json:"-"`
	Name         *string    `gorm:"column:name;index:idx_name,priority:1;index:idx_name_company_id,priority:1;comment:oneline" json:"-"` // oneline
	Address      *string    `gorm:"column:address" json:"-"`
	RegisterTime *time.Time `gorm:"column:register_time" json:"-"`
	/*
		column multiline /*comment* /
		line1
		line2
		colon:colon
		semicolon:semicolon
		"quotation mark"
		`accent`
	*/
	Alive      *bool   `gorm:"column:alive;comment:column multiline /*comment*/\nline1\nline2\ncolon colon\nsemicolon semicolon\n\"quotation mark\"\n'accent'" json:"-"`
	CompanyID  *int64  `gorm:"column:company_id;index:idx_name_company_id,priority:2;default:666" json:"-"`
	PrivateURL *string `gorm:"column:private_url;default:https://a.b.c" json:"-"`
}

func (m *User) IsEmpty() bool {
	if m == nil {
		return true
	}
	return m.ID == 0
}

func (m *User) GetID() int {
	return int(m.ID)
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
