// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package xxx

import (
	"time"

	"gorm.io/gorm"
)

const TableNameStudent = "students"

// students
type Student struct {
	ID        int64          `json:"id" gorm:"column:id"`
	CreatedAt time.Time      `json:"created_at" gorm:"column:created_at"`
	UpdatedAt time.Time      `json:"updated_at" gorm:"column:updated_at"`
	DeletedAt gorm.DeletedAt `json:"deleted_at" gorm:"column:deleted_at"`
	Num       int64          `json:"num" gorm:"column:num"`
	Name      string         `json:"name" gorm:"column:name"`
}

// TableName Student's table name
func (*Student) TableName() string {
	return TableNameStudent
}
