// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMytable = "mytables"

// Mytable mapped from table <mytables>
type Mytable struct {
	ID       int32  `gorm:"column:ID;primaryKey" json:"ID"`
	Username string `gorm:"column:username" json:"username"`
	Age      int32  `gorm:"column:age;not null" json:"age"`
	Phone    string `gorm:"column:phone;not null" json:"phone"`
}

func init() {
	RegisterModel(&Mytable{}, TableNameMytable)
}

// TableName Mytable's table name
func (*Mytable) TableName() string {
	return TableNameMytable
}
