// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEvent = "events"

// Event mapped from table <events>
type Event struct {
	ID      string `gorm:"column:id;primaryKey;default:uuid()" json:"id"`
	Payload string `gorm:"column:payload" json:"payload"`
}

// TableName Event's table name
func (*Event) TableName() string {
	return TableNameEvent
}
