// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string         `gorm:"column:name" json:"name"`
	Age       string         `gorm:"column:age" json:"age"`
	Address   string         `gorm:"column:address" json:"address"`
	Role      string         `gorm:"column:role" json:"role"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Remark    string         `gorm:"column:remark" json:"remark"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
