// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gen/helper"

	"gorm.io/gen/tests/.gen/dal_generic/model"

	"time"
)

func newUser(db *gorm.DB, opts ...gen.DOOption) user {
	_user := user{}

	_user.userDo.IWithDO = gen.WithDOFunc[IUserDo](_user.userDo.withDO)

	_user.userDo.UseDB(db, opts...)
	_user.userDo.UseModel(&model.User{})

	tableName := _user.userDo.TableName()
	_user.ALL = field.NewAsterisk(tableName)
	_user.ID = field.NewInt64(tableName, "id")
	_user.CreatedAt = field.NewTime(tableName, "created_at")
	_user.Name = field.NewString(tableName, "name")
	_user.Address = field.NewString(tableName, "address")
	_user.RegisterTime = field.NewTime(tableName, "register_time")
	_user.Alive = field.NewBool(tableName, "alive")
	_user.CompanyID = field.NewInt64(tableName, "company_id")
	_user.PrivateURL = field.NewString(tableName, "private_url")

	_user.fillFieldMap()

	return _user
}

type user struct {
	userDo userDo

	ALL          field.Asterisk
	ID           field.Int64
	CreatedAt    field.Time
	Name         field.String // oneline
	Address      field.String
	RegisterTime field.Time
	/*
		multiline
		line1
		line2
	*/
	Alive      field.Bool
	CompanyID  field.Int64
	PrivateURL field.String

	fieldMap map[string]field.Expr
}

func (u user) Table(newTableName string) *user {
	u.userDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u user) As(alias string) *user {
	u.userDo.DO = *(u.userDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *user) updateTableName(table string) *user {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.Name = field.NewString(table, "name")
	u.Address = field.NewString(table, "address")
	u.RegisterTime = field.NewTime(table, "register_time")
	u.Alive = field.NewBool(table, "alive")
	u.CompanyID = field.NewInt64(table, "company_id")
	u.PrivateURL = field.NewString(table, "private_url")

	u.fillFieldMap()

	return u
}

func (u *user) WithContext(ctx context.Context) IUserDo { return u.userDo.WithContext(ctx) }

func (u user) TableName() string { return u.userDo.TableName() }

func (u user) Alias() string { return u.userDo.Alias() }

func (u user) Columns(cols ...field.Expr) gen.Columns { return u.userDo.Columns(cols...) }

func (u *user) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *user) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 8)
	u.fieldMap["id"] = u.ID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["name"] = u.Name
	u.fieldMap["address"] = u.Address
	u.fieldMap["register_time"] = u.RegisterTime
	u.fieldMap["alive"] = u.Alive
	u.fieldMap["company_id"] = u.CompanyID
	u.fieldMap["private_url"] = u.PrivateURL
}

func (u user) clone(db *gorm.DB) user {
	u.userDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u user) replaceDB(db *gorm.DB) user {
	u.userDo.ReplaceDB(db)
	return u
}

type userDo struct {
	gen.GenericsDo[IUserDo, *model.User]
}
type IUserDo interface {
	gen.IGenericsDo[IUserDo, *model.User]
	FindByUsers(user model.User) (result []model.User)
	FindByComplexIf(user *model.User) (result []model.User)
	FindByIfTime(start time.Time) (result []model.User)
	TestFor(names []string) (result model.User, err error)
	TestForKey(names []string, name string, value string) (result model.User, err error)
	TestForOr(names []string) (result model.User, err error)
	TestIfInFor(names []string, name string) (result model.User, err error)
	TestForInIf(names []string, name string) (result model.User, err error)
	TestForInWhere(names []string, name string, forName string) (result model.User, err error)
	TestForUserList(users []*model.User, name string) (result model.User, err error)
	TestForMap(param map[string]string, name string) (result model.User, err error)
	TestIfInIf(name string) (result model.User)
	TestMoreFor(names []string, ids []int) (result []model.User)
	TestMoreFor2(names []string, ids []int) (result []model.User)
	TestForInSet(users []model.User) (err error)
	TestInsertMoreInfo(users []model.User) (err error)
	TestIfElseFor(name string, users []model.User) (err error)
	TestForLike(names []string) (result []model.User)
	AddUser(name string, age int) (result sql.Result, err error)
	AddUser1(name string, age int) (rowsAffected int64, err error)
	AddUser2(name string, age int) (rowsAffected int64)
	AddUser3(name string, age int) (result sql.Result)
	AddUser4(name string, age int) (row *sql.Row)
	AddUser5(name string, age int) (rows *sql.Rows)
	AddUser6(name string, age int) (rows *sql.Rows, err error)
	FindByID(id int) (result model.User)
	LikeSearch(name string) (result *model.User)
	InSearch(names []string) (result []*model.User)
	ColumnSearch(name string, names []string) (result []*model.User)
}

// FindByUsers
//
// select * from @@table
// {{where}}
// {{if user.Name !=""}}
// name=@user.Name
// {{end}}
// {{end}}
func (u userDo) FindByUsers(user model.User) (result []model.User) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	if user.Name != "" {
		params = append(params, user.Name)
		whereSQL0.WriteString("name=? ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// FindByComplexIf
//
// select * from @@table
// {{where}}
// {{if user != nil && user.Name !=""}}
// name=@user.Name
// {{end}}
// {{end}}
func (u userDo) FindByComplexIf(user *model.User) (result []model.User) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	if user != nil && user.Name != "" {
		params = append(params, user.Name)
		whereSQL0.WriteString("name=? ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// FindByIfTime
//
// select * from @@table
// {{if !start.IsZero()}}
// created_at > start
// {{end}}
func (u userDo) FindByIfTime(start time.Time) (result []model.User) {
	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	if !start.IsZero() {
		generateSQL.WriteString("created_at > start ")
	}

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String()).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// TestFor
//
// select * from @@table where
// {{for _,name:=range names}}
// name = @name and
// {{end}}
// 1=1
func (u userDo) TestFor(names []string) (result model.User, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users where ")
	for _, name := range names {
		params = append(params, name)
		generateSQL.WriteString("name = ? and ")
	}
	generateSQL.WriteString("1=1 ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestForKey
//
// select * from @@table where
// {{for _,name:=range names}}
// or @@name = @value
// {{end}}
// and 1=1
func (u userDo) TestForKey(names []string, name string, value string) (result model.User, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users where ")
	for _, name := range names {
		params = append(params, value)
		generateSQL.WriteString("or " + u.Quote(name) + " = ? ")
	}
	generateSQL.WriteString("and 1=1 ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestForOr
//
// select * from @@table
// {{where}}
// (
// {{for _,name:=range names}}
// name = @name or
// {{end}}
// {{end}}
// )
func (u userDo) TestForOr(names []string) (result model.User, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	whereSQL0.WriteString("( ")
	for _, name := range names {
		params = append(params, name)
		whereSQL0.WriteString("name = ? or ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)
	generateSQL.WriteString(") ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestIfInFor
//
// select * from @@table where
// {{for _,name:=range names}}
// {{if name !=""}}
// name = @name or
// {{end}}
// {{end}}
// 1=2
func (u userDo) TestIfInFor(names []string, name string) (result model.User, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users where ")
	for _, name := range names {
		if name != "" {
			params = append(params, name)
			generateSQL.WriteString("name = ? or ")
		}
	}
	generateSQL.WriteString("1=2 ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestForInIf
//
// select * from @@table where
// {{if name !="" }}
// {{for _,forName:=range names}}
// name = @forName or
// {{end}}
// {{end}}
// 1=2
func (u userDo) TestForInIf(names []string, name string) (result model.User, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users where ")
	if name != "" {
		for _, forName := range names {
			params = append(params, forName)
			generateSQL.WriteString("name = ? or ")
		}
	}
	generateSQL.WriteString("1=2 ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestForInWhere
//
// select * from @@table
// {{where}}
// {{for _,forName:=range names}}
// or name = @forName
// {{end}}
// {{end}}
func (u userDo) TestForInWhere(names []string, name string, forName string) (result model.User, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	for _, forName := range names {
		params = append(params, forName)
		whereSQL0.WriteString("or name = ? ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestForUserList
//
// select * from users
// {{where}}
// {{for _,user :=range users}}
// name=@user.Name
// {{end}}
// {{end}}
func (u userDo) TestForUserList(users []*model.User, name string) (result model.User, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	for _, user := range users {
		params = append(params, user.Name)
		whereSQL0.WriteString("name=? ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestForMap
//
// select * from users
// {{where}}
// {{for key,value :=range param}}
// @@key=@value
// {{end}}
// {{end}}
func (u userDo) TestForMap(param map[string]string, name string) (result model.User, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	for key, value := range param {
		params = append(params, value)
		whereSQL0.WriteString(u.Quote(key) + "=? ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestIfInIf
//
// select * from users
// {{where}}
// {{if name !="xx"}}
// {{if name !="xx"}}
// name=@name
// {{end}}
// {{end}}
// {{end}}
func (u userDo) TestIfInIf(name string) (result model.User) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	if name != "xx" {
		if name != "xx" {
			params = append(params, name)
			whereSQL0.WriteString("name=? ")
		}
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// TestMoreFor
//
// select * from @@table
// {{where}}
// {{for _,name := range names}}
// and name=@name
// {{end}}
// {{for _,id:=range ids}}
// and id=@id
// {{end}}
// {{end}}
func (u userDo) TestMoreFor(names []string, ids []int) (result []model.User) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	for _, name := range names {
		params = append(params, name)
		whereSQL0.WriteString("and name=? ")
	}
	for _, id := range ids {
		params = append(params, id)
		whereSQL0.WriteString("and id=? ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// TestMoreFor2
//
// select * from @@table
// {{where}}
// {{for _,name := range names}}
// OR (name=@name
// {{for _,id:=range ids}}
// and id=@id
// {{end}}
// and title !=@name)
// {{end}}
// {{end}}
func (u userDo) TestMoreFor2(names []string, ids []int) (result []model.User) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	for _, name := range names {
		params = append(params, name)
		whereSQL0.WriteString("OR (name=? ")
		for _, id := range ids {
			params = append(params, id)
			whereSQL0.WriteString("and id=? ")
		}
		params = append(params, name)
		whereSQL0.WriteString("and title !=?) ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// TestForInSet
//
// update @@table
// {{set}}
// {{for _,user:=range users}}
// name=@user.Name,
// {{end}}
// {{end}} where
func (u userDo) TestForInSet(users []model.User) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("update users ")
	var setSQL0 strings.Builder
	for _, user := range users {
		params = append(params, user.Name)
		setSQL0.WriteString("name=?, ")
	}
	helper.JoinSetBuilder(&generateSQL, setSQL0)
	generateSQL.WriteString("where ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestInsertMoreInfo
//
// insert into @@table(name,age)values
// {{for index ,user:=range users}}
// {{if index >0}}
// ,
// {{end}}
// (@user.Name,@user.Age)
// {{end}}
func (u userDo) TestInsertMoreInfo(users []model.User) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("insert into users(name,age)values ")
	for index, user := range users {
		if index > 0 {
			generateSQL.WriteString(", ")
		}
		params = append(params, user.Name)
		params = append(params, user.Age)
		generateSQL.WriteString("(?,?) ")
	}

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestIfElseFor
//
// select * from @@table
// {{where}}
// {{if name =="admin"}}
// (
// {{for index,user:=range users}}
// {{if index !=0}}
// and
// {{end}}
// name like @user.Name
// {{end}}
// )
// {{else if name !="guest"}}
// {{for index,guser:=range users}}
// {{if index ==0}}
// (
// {{else}}
// and
// {{end}}
// name = @guser.Name
// {{end}}
// )
// {{else}}
// name ="guest"
// {{end}}
// {{end}}
func (u userDo) TestIfElseFor(name string, users []model.User) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	if name == "admin" {
		whereSQL0.WriteString("( ")
		for index, user := range users {
			if index != 0 {
				whereSQL0.WriteString("and ")
			}
			params = append(params, user.Name)
			whereSQL0.WriteString("name like ? ")
		}
		whereSQL0.WriteString(") ")
	} else if name != "guest" {
		for index, guser := range users {
			if index == 0 {
				whereSQL0.WriteString("( ")
			} else {
				whereSQL0.WriteString("and ")
			}
			params = append(params, guser.Name)
			whereSQL0.WriteString("name = ? ")
		}
		whereSQL0.WriteString(") ")
	} else {
		whereSQL0.WriteString("name =\"guest\" ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestForLike
//
// select * from @@table
// {{where}}
// {{for _,name:=range names}}
// name like concat("%",@name,"%") or
// {{end}}
// {{end}}
func (u userDo) TestForLike(names []string) (result []model.User) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	for _, name := range names {
		params = append(params, name)
		whereSQL0.WriteString("name like concat(\"%\",?,\"%\") or ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// AddUser
//
// INSERT INTO users (name,age) VALUES (@name,@age) ON DUPLICATE KEY UPDATE age=VALUES(age)
func (u userDo) AddUser(name string, age int) (result sql.Result, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	params = append(params, age)
	generateSQL.WriteString("INSERT INTO users (name,age) VALUES (?,?) ON DUPLICATE KEY UPDATE age=VALUES(age) ")

	stmt := u.UnderlyingDB().Statement
	result, err = stmt.ConnPool.ExecContext(stmt.Context, generateSQL.String(), params...) // ignore_security_alert

	return
}

// AddUser1
//
// INSERT INTO users (name,age) VALUES (@name,@age) ON DUPLICATE KEY UPDATE age=VALUES(age)
func (u userDo) AddUser1(name string, age int) (rowsAffected int64, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	params = append(params, age)
	generateSQL.WriteString("INSERT INTO users (name,age) VALUES (?,?) ON DUPLICATE KEY UPDATE age=VALUES(age) ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	rowsAffected = executeSQL.RowsAffected
	err = executeSQL.Error

	return
}

// AddUser2
//
// INSERT INTO users (name,age) VALUES (@name,@age) ON DUPLICATE KEY UPDATE age=VALUES(age)
func (u userDo) AddUser2(name string, age int) (rowsAffected int64) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	params = append(params, age)
	generateSQL.WriteString("INSERT INTO users (name,age) VALUES (?,?) ON DUPLICATE KEY UPDATE age=VALUES(age) ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	rowsAffected = executeSQL.RowsAffected

	return
}

// AddUser3
//
// INSERT INTO users (name,age) VALUES (@name,@age) ON DUPLICATE KEY UPDATE age=VALUES(age)
func (u userDo) AddUser3(name string, age int) (result sql.Result) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	params = append(params, age)
	generateSQL.WriteString("INSERT INTO users (name,age) VALUES (?,?) ON DUPLICATE KEY UPDATE age=VALUES(age) ")

	stmt := u.UnderlyingDB().Statement
	result, _ = stmt.ConnPool.ExecContext(stmt.Context, generateSQL.String(), params...) // ignore_security_alert

	return
}

// AddUser4
//
// INSERT INTO users (name,age) VALUES (@name,@age) ON DUPLICATE KEY UPDATE age=VALUES(age)
func (u userDo) AddUser4(name string, age int) (row *sql.Row) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	params = append(params, age)
	generateSQL.WriteString("INSERT INTO users (name,age) VALUES (?,?) ON DUPLICATE KEY UPDATE age=VALUES(age) ")

	row = u.UnderlyingDB().Raw(generateSQL.String(), params...).Row() // ignore_security_alert

	return
}

// AddUser5
//
// INSERT INTO users (name,age) VALUES (@name,@age) ON DUPLICATE KEY UPDATE age=VALUES(age)
func (u userDo) AddUser5(name string, age int) (rows *sql.Rows) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	params = append(params, age)
	generateSQL.WriteString("INSERT INTO users (name,age) VALUES (?,?) ON DUPLICATE KEY UPDATE age=VALUES(age) ")

	rows, _ = u.UnderlyingDB().Raw(generateSQL.String(), params...).Rows() // ignore_security_alert

	return
}

// AddUser6
//
// INSERT INTO users (name,age) VALUES (@name,@age) ON DUPLICATE KEY UPDATE age=VALUES(age)
func (u userDo) AddUser6(name string, age int) (rows *sql.Rows, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	params = append(params, age)
	generateSQL.WriteString("INSERT INTO users (name,age) VALUES (?,?) ON DUPLICATE KEY UPDATE age=VALUES(age) ")

	rows, err = u.UnderlyingDB().Raw(generateSQL.String(), params...).Rows() // ignore_security_alert

	return
}

// FindByID
//
// select * from users where id=@id
func (u userDo) FindByID(id int) (result model.User) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("select * from users where id=? ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// LikeSearch
//
// SELECT * FROM @@table where name LIKE concat('%',@name,'%')
func (u userDo) LikeSearch(name string) (result *model.User) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	generateSQL.WriteString("SELECT * FROM users where name LIKE concat('%',?,'%') ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// InSearch
//
// select * from @@table where name in @names
func (u userDo) InSearch(names []string) (result []*model.User) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, names)
	generateSQL.WriteString("select * from users where name in ? ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// ColumnSearch
//
// select * from @@table where @@name in @names
func (u userDo) ColumnSearch(name string, names []string) (result []*model.User) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, names)
	generateSQL.WriteString("select * from users where " + u.Quote(name) + " in ? ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

func (u *userDo) withDO(do gen.Dao) IUserDo {
	_r := &userDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[IUserDo](u.withDO)
	return _r
}
