// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID          int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 用户id
	Name        string         `gorm:"column:name;not null" json:"name"`                  // 姓名
	Age         int32          `gorm:"column:age" json:"age"`
	Password    string         `gorm:"column:password" json:"password"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Title       string         `gorm:"column:title" json:"title"`
	IsAdult     int32          `gorm:"column:is_adult;default:0" json:"is_adult"`
	UpdatedTime time.Time      `gorm:"column:updated_time" json:"updated_time"`
	Pass        string         `gorm:"column:pass" json:"pass"`
	Role        string         `gorm:"column:role" json:"role"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	Address     string         `gorm:"column:address" json:"address"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
