// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package myquery

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	ChargePoint     *chargePoint
	ChargingStation *chargingStation
	City            *city
	PowerSocket     *powerSocket
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	ChargePoint = &Q.ChargePoint
	ChargingStation = &Q.ChargingStation
	City = &Q.City
	PowerSocket = &Q.PowerSocket
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		ChargePoint:     newChargePoint(db, opts...),
		ChargingStation: newChargingStation(db, opts...),
		City:            newCity(db, opts...),
		PowerSocket:     newPowerSocket(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ChargePoint     chargePoint
	ChargingStation chargingStation
	City            city
	PowerSocket     powerSocket
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		ChargePoint:     q.ChargePoint.clone(db),
		ChargingStation: q.ChargingStation.clone(db),
		City:            q.City.clone(db),
		PowerSocket:     q.PowerSocket.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		ChargePoint:     q.ChargePoint.replaceDB(db),
		ChargingStation: q.ChargingStation.replaceDB(db),
		City:            q.City.replaceDB(db),
		PowerSocket:     q.PowerSocket.replaceDB(db),
	}
}

type queryCtx struct {
	ChargePoint     IChargePointDo
	ChargingStation IChargingStationDo
	City            ICityDo
	PowerSocket     IPowerSocketDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ChargePoint:     q.ChargePoint.WithContext(ctx),
		ChargingStation: q.ChargingStation.WithContext(ctx),
		City:            q.City.WithContext(ctx),
		PowerSocket:     q.PowerSocket.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
