package template

const NotEditMark = `
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
`

const Header = NotEditMark + `
package {{.}}

import(
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/schema"
	"gorm.io/gorm/clause"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gen/helper"
)
`

const UnitTestHeader = NotEditMark + `
package {{.}}

import(
	"context"
	"fmt"
	"testing"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)
`
